server:
  port: 8088
  servlet:
    context-path: /api
spring:
  #数据库信息配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-dq4lwxcu.sql.tencentcdb.com:20065/gptMgmt?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: Ican_2023
  # MyBatis配置文件
mybatis:
  mapper-locations: com/hsbc/insh/mapper/*Mapper.xml

serve:
  python:
    addDBDocs: http://localhost:80/api/v2/addDBDocs #http://150.158.173.37:83/
    removeDBDocs: http://localhost:80/api/v2/removeDBDocs #http://150.158.173.37:83/
